### PR TITLE
Fill background using color from theme

### PR DESCRIPTION
**Pull request by VisenDev**

### CODE REVIEW

**Comment by david-vanderson** [comment]
This brings up the question of what exactly `backend.clear()` should be doing.  For -ontop situations, I see it as a stand-in for the app/games own rendering.  For -standalone situations, dvui widgets should cover the window, and the user should never see this right?

What are you thinking here?

**Comment by VisenDev** [comment]
> This brings up the question of what exactly `backend.clear()` should be doing. For -ontop situations, I see it as a stand-in for the app/games own rendering. For -standalone situations, dvui widgets should cover the window, and the user should never see this right?
> 
> What are you thinking here?

If those are the only two uses of `clear()` then the function could probably be removed. For ontop you can just call the appropriate c function for that backend to accomplish this

**Comment by VisenDev** [comment]
I branched my other PR off of this one so this one is kind of unnecessary

**Comment by david-vanderson** [comment]
Yes I think you are right - I'll remove `clear()` from the backends.

**Pull request closed without merging**
