### PR TITLE
make it easy to use as dependency

### PR DESCRIPTION
**Pull request by iacore**
this is the hackiest code I've written this year

### CODE REVIEW

**Comment by david-vanderson** [comment]
Well done!  Would you mind if I swapped out the example build.zig stuff for a prominent link to the dvui-demo build.zig?  I always worry about docs getting out of date, but I see that the dvui-demo link is easy to miss.  Let me try it and I'll follow up to ask how it looks to you.

Thanks very much!

**Comment by david-vanderson** [comment]
Okay I liked having the build.zig stuff right in the docs, so I only made some minor edits.  Look okay?

**Comment by david-vanderson** [comment]
Cool.  Sorry I'm confused - what new file?

**Comment by iacore** [comment]
it was `INSIDE.md`

**Comment by david-vanderson** [comment]
Ah I see - thanks!

**Pull request merged**
