### PR TITLE
Struct Widget Experiments

### PR DESCRIPTION
**Pull request by VisenDev**
This PR's purpose is to share my experiments addressing https://github.com/david-vanderson/dvui/issues/101 in the hopes that they will be useful

**TODO**
- [x] ~~Swap structEntry to use `Miller Columns` instead of expanders for sub-structs~~     (**Expanders are better**)
- [ ] Add functionality for disabling certain fields 
- [ ] Implement copying and pasting of structEntry sub-entries via std.json serialization
- [x] Implement FieldOptions for all types
- [ ] Implement Arrays, Slices, and Vectors via reorderable lists. Depends on #109

### CODE REVIEW

**Comment by VisenDev** [comment]
So here is the idea for the `field_options` parameter. Dvui constructs a struct type based off of the input type, it contains the same field names, but the field types are instead a `TypeOptions` corresponding to the type. Thus, specific options can be passed in to change how different field widget inputs get rendered, like so

```zig
        const TestType = struct {
            a: i8,
            b: u16,
            c: f32,
            g: f64,
            foo: bool,
            bar: dvui.Color,
            bap: enum { red, green, blue, bip },
        };
        var result: TestType = undefined;
        try dvui.structWidget(@src(), TestType, &result, .{
            .a = .{ .widget_type = .slider },
            .foo = .{ .widget_type = .toggle },
            .bar = .{
                .r = .{ .widget_type = .slider },
                .g = .{ .widget_type = .slider },
                .b = .{ .widget_type = .slider },
            },
        });
```

Notably, this does not just accept `anytype`, it actually constructs a corresponding specific `options` type for every struct at comptime.

All of this configuration code is now working - what needs to be done next is actually write the `intInputWidget` and `floatInputWidget` and so on

**Comment by VisenDev** [comment]
Example of simple label layout generated from a `TestType`. No input widgets implemented yet

Screenshot 2024-08-13 at 2 38 20 PM

**Comment by VisenDev** [comment]
More input widgets working
Screenshot 2024-08-17 at 10 25 07 AM

**Comment by david-vanderson** [comment]
This is very cool

**Comment by VisenDev** [comment]
Basic input functionality should be working for most types. I still have a lot of work left on adjusting the UI layout so things look right.

Slice, Array, and Vector types are not really fully developed yet

Sample of a `structEntry` generated from a `dvui.Theme`

Screenshot 2024-08-19 at 2 48 26 PM

**Comment by VisenDev** [comment]
@david-vanderson I've got the basic experimental things working here now. I think what I have is good as an initial implementation and I can finish up adding the features I want in future PRs.

**Comment by david-vanderson** [comment]
Awesome!  Will look at it in the next day or 2.  Thanks!

**Comment by david-vanderson** [comment]
Looks good enough to merge and we can keep working on it in main.  Great work!

**Comment by david-vanderson** [comment]
We might step on each other's toes while working on it, and I might make some changes you don't like.  If that happens please let me know so we can sort it out and make this awesome.

**Comment by VisenDev** [comment]
> We might step on each other's toes while working on it, and I might make some changes you don't like. If that happens please let me know so we can sort it out and make this awesome.

Sounds good

**Pull request merged**
