### PR TITLE
autodoc

### PR DESCRIPTION
**Pull request by VisenDev**
Added autodocs generation

To test autodocs locally, you need to run a http server on localhost and connect in your browser. The easiest way I've discovered to do this is to run `python -m http.server` in `zig-out/docs`. Then you can connect to `http://localhost:8000` in your browser

2024-10-09-092235_hyprshot

### CODE REVIEW

**Comment by iacore** [comment]
Nice. Maybe we could copy the `zig std` http server to this repo and run it at `zig build docs`.

**Comment by VisenDev** [comment]
> Or, publish the docs somewhere, like Github pages with CI.

I presumed that is what david would want to do once he was happy with it (similar to how the web example works)

**Comment by david-vanderson** [comment]
Thanks very much!  Yes - I will publish them to github pages alongside the demo.

**Comment by david-vanderson** [comment]
Is there a reason to not build the docs by default with `zig build`?

**Comment by iacore** [comment]
> Is there a reason to not build the docs by default with `zig build`?

it takes time?

**Comment by VisenDev** [comment]
> > Is there a reason to not build the docs by default with `zig build`?
> 
> That it takes time?

Other than that, building it by default should be fine

**Comment by david-vanderson** [comment]
Will have it build by default and see how that affects development speed.

**Pull request merged**
