### PR TITLE
Add sdl3 support

### PR DESCRIPTION
**Pull request by Deins**
Currently compiles sdl3 from source - build scripts dependency supports windows only. 
I assume for linux using sdl3 from system should be straight forward but haven't implemented build config or looked into.

Backend can be compiled run with:
```
zig build sdl-standalone -Dsdl3
zig build sdl-ontop -Dsdl3 
```
SDL2 config should work as before - unchanged. 

relates to: https://github.com/david-vanderson/dvui/issues/143

### CODE REVIEW

**Comment by david-vanderson** [comment]
This is fantastic - thank you!  First question - `@import("sdl3_c")` - what module is that importing?

**Comment by Deins** [comment]
https://github.com/david-vanderson/dvui/blob/53f0379ed43297be03509609e69511321e3fdb4a/build.zig#L231
its https://github.com/swan-www/zig_sdl3/ dependancy, it already provides translated-c module.

**Comment by david-vanderson** [comment]
Thank you - can't believe I missed that!  Give me some time to dig into it.

**Comment by david-vanderson** [comment]
`_ = winapi.AttachConsole(0xFFFFFFFF);` - I can't seem to see how this makes a difference, how do I run sdl-standalone to see what this does?

Otherwise, this looks very good.  Actually compiling the sdl3 doesn't currently work on my windows machine (seems to be missing some windows sdk stuff).  But since it's behind a zig build option I think we merge and continue the work on main.

Thank you!

**Comment by Deins** [comment]
forgot to take it out, `AttachConsole` is unrelated change just for debug, without it stdout/stderr doesn't get printed in console/terminal when program is launched. Can be tested ` with `std.debug.print("TEST\n", .{});` or std.log.

**Comment by david-vanderson** [comment]
Aha got it.  Will think about whether we should keep it in.

For anyone following along, it makes debug output show up in Windows cmd console when running `zig build sdl-standalone` or directly running the binary `.\zig-out\bin\sdl-standalone`.

I normally run the git-bash mingw console on windows.  In that (regardless of whether we run AttachConsole) I never see the output when running `zig build` but do see it when directly running the binary.

**Comment by Deins** [comment]
Also pushed linux support, linking sdl3 from system: https://github.com/david-vanderson/dvui/commit/6bedaf83b9a63a9caf6d195fe0ed479370f2fdf9
Tested on ubuntu 22 in WSL, SDL3 compiled and installed from source on system following SDL3 build instructions. 
Kept flag wise that `-Dsdl3` is for configurations built from source (currently windows only) and `-fsys=sdl3` when linking against system library in case on some platforms bot configurations can be supported.

**Comment by david-vanderson** [comment]
Awesome thank you!

**Pull request merged**
