### PR TITLE
Use OKHSL for colors

### LINKED ISSUE #56: use proper colorspace for color operations
cannot lighten black

`0 * (1 + y) == 0`

https://github.com/david-vanderson/dvui/blob/811e8d93f9f55c0a16d18d45e61a2db646198b52/src/Color.zig#L28-L35

### PR DESCRIPTION
**Pull request by iacore**
Second try's a charm.

Fixes #56.

### CODE REVIEW

**Comment by iacore** [comment]
Oh no. The window borders are now gone :scream:

See the `ok_color` branch in this repo.

**Comment by iacore** [comment]
I'm now getting NaN. Great.

**Comment by david-vanderson** [comment]
Sorry I haven't gotten to this yet, but I did think that we could use the header as-is instead of translating it to zig.  We could bundle it into the same static lib that the stb_* stuff goes into.  Does that help?

**Comment by iacore** [comment]
> Sorry I haven't gotten to this yet, but I did think that we could use the header as-is instead of translating it to zig. We could bundle it into the same static lib that the stb_* stuff goes into. Does that help?

`Adwaita.zig` uses that at comptime. not good.

**Comment by david-vanderson** [comment]
Ah right.  Well hang on a little longer and hopefully I can figure something out here.

**Pull request merged**
