### PR TITLE
Initial work on raylib backend

### PR DESCRIPTION
**Pull request by VisenDev**

### CODE REVIEW

**Comment by wwderw** [comment]
As I big fan of raylib, I'm looking forward to this.

**Comment by david-vanderson** [comment]
You are beating me to it!  Here's how far I've gotten with renderGeometry, it's only trying to render a rectangle with an antialias fringe and in the normal opengl coords.

```zig
pub fn renderGeometry(self: *RaylibBackend, texture: ?*anyopaque, _: []const dvui.Vertex, _: []const u32) void {
    // TODO: scissor
    // TODO: texture
    _ = self;
    _ = texture;

    // for testing
    const rgb = dvui.Color{ .r = 14, .g = 14, .b = 96, .a = 0xff };
    const rgb_trans = dvui.Color{ .r = 14, .g = 14, .b = 96, .a = 0 };
    const vtx = &[_]dvui.Vertex{
        dvui.Vertex{ .pos = dvui.Point{ .x = 0.5535534, .y = 0.5535534 }, .col = rgb, .uv = .{ -3.0316488e-13, -3.0316488e-13 } },
        dvui.Vertex{ .pos = dvui.Point{ .x = -0.15355338, .y = -0.15355338 }, .col = rgb_trans, .uv = .{ -3.0316488e-13, -3.0316488e-13 } },
        dvui.Vertex{ .pos = dvui.Point{ .x = 0.5535534, .y = -0.053553373 }, .col = rgb, .uv = .{ -3.0316488e-13, -3.0316488e-13 } },
        dvui.Vertex{ .pos = dvui.Point{ .x = -0.15355338, .y = 0.65355337 }, .col = rgb_trans, .uv = .{ -3.0316488e-13, -3.0316488e-13 } },
        dvui.Vertex{ .pos = dvui.Point{ .x = -0.053553373, .y = -0.053553373 }, .col = rgb, .uv = .{ -3.0316488e-13, -3.0316488e-13 } },
        dvui.Vertex{ .pos = dvui.Point{ .x = 0.65355337, .y = 0.65355337 }, .col = rgb_trans, .uv = .{ -3.0316488e-13, -3.0316488e-13 } },
        dvui.Vertex{ .pos = dvui.Point{ .x = -0.053553373, .y = 0.5535534 }, .col = rgb, .uv = .{ -3.0316488e-13, -3.0316488e-13 } },
        dvui.Vertex{ .pos = dvui.Point{ .x = 0.65355337, .y = -0.15355338 }, .col = rgb_trans, .uv = .{ -3.0316488e-13, -3.0316488e-13 } },
    };

    const idx = &[_]u32{
        6, 7, 0, 7, 1, 0, 0, 1, 2, 1, 3, 2, 0, 2, 4, 2, 3, 4, 3, 5, 4, 0, 4, 6, 4, 5, 6, 5, 7, 6,
    };

    //std.debug.print("renderGeometry vtx.len {d}\n", .{vtx.len});

    const vertexSource =
        \\#version 330
        \\in vec3 vertexPosition;
        //"in vec2 vertexTexCoord;            \n"
        \\in vec4 vertexColor;
        //"out vec2 fragTexCoord;             \n"
        \\out vec4 fragColor;
        //\\uniform mat4 mvp;
        \\void main()
        \\{
        //"    fragTexCoord = vertexTexCoord; \n"
        \\    fragColor = vertexColor / 255.0;
        //\\    fragColor.rgb *= fragColor.a;
        //\\    gl_Position = mvp*vec4(vertexPosition, 1.0); \n"
        \\    gl_Position = vec4(vertexPosition, 1.0);
        \\}
    ;

    const fragSource =
        \\#version 330
        //"in vec2 fragTexCoord;              \n"
        \\in vec4 fragColor;
        \\out vec4 finalColor;
        //"uniform sampler2D texture0;        \n"
        //"uniform vec4 colDiffuse;           \n"
        //"void main()                        \n"
        //"{                                  \n"
        //"    vec4 texelColor = texture(texture0, fragTexCoord);   \n"
        //"    finalColor = texelColor*colDiffuse*fragColor;        \n"
        //"}                                  \n";
        \\void main()
        \\{
        \\    finalColor = fragColor;
        \\}
    ;

    // use default shaders
    const shader = c.LoadShaderFromMemory(vertexSource, fragSource);
    //const shader = c.LoadShaderFromMemory(null, null);

    const VAO = c.rlLoadVertexArray();
    _ = c.rlEnableVertexArray(VAO);

    const VBO = c.rlLoadVertexBuffer(vtx.ptr, @intCast(vtx.len * @sizeOf(dvui.Vertex)), false);
    _ = VBO;
    const EBO = c.rlLoadVertexBufferElement(idx.ptr, @intCast(idx.len * @sizeOf(u32)), false);
    _ = EBO;

    c.rlSetVertexAttribute(@intCast(shader.locs[c.RL_SHADER_LOC_VERTEX_POSITION]), 2, c.RL_FLOAT, false, @sizeOf(dvui.Vertex), @offsetOf(dvui.Vertex, "pos"));
    c.rlEnableVertexAttribute(@intCast(shader.locs[c.RL_SHADER_LOC_VERTEX_POSITION]));

    c.rlSetVertexAttribute(@intCast(shader.locs[c.RL_SHADER_LOC_VERTEX_COLOR]), 4, c.RL_UNSIGNED_BYTE, false, @sizeOf(dvui.Vertex), @offsetOf(dvui.Vertex, "col"));
    c.rlEnableVertexAttribute(@intCast(shader.locs[c.RL_SHADER_LOC_VERTEX_COLOR]));

    c.rlEnableShader(shader.id);

    c.glDrawElements(c.GL_TRIANGLES, @intCast(idx.len), c.GL_UNSIGNED_INT, null);
}
```

**Comment by david-vanderson** [comment]
Screenshot from 2024-07-30 20-17-29
Unfortunately it doesn't quite render correctly, and I'm not sure why.

**Comment by VisenDev** [comment]
> You are beating me to it! Here's how far I've gotten with renderGeometry, it's only trying to render a rectangle with an antialias fringe and in the normal opengl coords.

Oh I didn't realize you were working on it already! Looks like you are farther than I. I'm still trying to figure out how the backend interface works.

I assume I can close this PR then?

**Comment by david-vanderson** [comment]
Sadly I'm stuck and looking for help.  Is there any chance you can try to get that example code working better?

Let's leave this open for now because you got a lot of other stuff I hadn't looked at yet.

**Comment by david-vanderson** [comment]
Here's a standalone version of the problem not going through a backend.  If we can get this rendering correctly that'll help a lot.
```zig
const std = @import("std");
const dvui = @import("dvui");

pub const c = @cImport({
    @cInclude("raylib.h");
    @cInclude("rlgl.h");
    @cInclude("GLES3/gl3.h");
});

pub fn main() !void {
    c.InitWindow(800, 450, "raylib [core] example - basic window");

    main_loop: while (true) {

        // send all SDL events to dvui for processing
        const quit = c.WindowShouldClose();
        if (quit) break :main_loop;

        c.ClearBackground(c.BLACK);

        c.BeginDrawing();

        //c.DrawText("Congrats! You created your first window!", 190, 200, 20, c.LIGHTGRAY);

        const rgb = dvui.Color{ .r = 10, .g = 180, .b = 100, .a = 255 };
        const rgb_trans = dvui.Color{ .r = 10, .g = 180, .b = 100, .a = 0 };
        const vtx = &[_]dvui.Vertex{
            dvui.Vertex{ .pos = dvui.Point{ .x = 0.5535534, .y = 0.5535534 }, .col = rgb, .uv = .{ -3.0316488e-13, -3.0316488e-13 } },
            dvui.Vertex{ .pos = dvui.Point{ .x = -0.15355338, .y = -0.15355338 }, .col = rgb_trans, .uv = .{ -3.0316488e-13, -3.0316488e-13 } },
            dvui.Vertex{ .pos = dvui.Point{ .x = 0.5535534, .y = -0.053553373 }, .col = rgb, .uv = .{ -3.0316488e-13, -3.0316488e-13 } },
            dvui.Vertex{ .pos = dvui.Point{ .x = -0.15355338, .y = 0.65355337 }, .col = rgb_trans, .uv = .{ -3.0316488e-13, -3.0316488e-13 } },
            dvui.Vertex{ .pos = dvui.Point{ .x = -0.053553373, .y = -0.053553373 }, .col = rgb, .uv = .{ -3.0316488e-13, -3.0316488e-13 } },
            dvui.Vertex{ .pos = dvui.Point{ .x = 0.65355337, .y = 0.65355337 }, .col = rgb_trans, .uv = .{ -3.0316488e-13, -3.0316488e-13 } },
            dvui.Vertex{ .pos = dvui.Point{ .x = -0.053553373, .y = 0.5535534 }, .col = rgb, .uv = .{ -3.0316488e-13, -3.0316488e-13 } },
            dvui.Vertex{ .pos = dvui.Point{ .x = 0.65355337, .y = -0.15355338 }, .col = rgb_trans, .uv = .{ -3.0316488e-13, -3.0316488e-13 } },
        };

        const idx = &[_]u32{
            6, 7, 0, 7, 1, 0, 0, 1, 2, 1, 3, 2, 0, 2, 4, 2, 3, 4, 3, 5, 4, 0, 4, 6, 4, 5, 6, 5, 7, 6,
        };

        //std.debug.print("renderGeometry vtx.len {d}\n", .{vtx.len});

        const vertexSource =
            \\#version 330
            \\in vec3 vertexPosition;
            //"in vec2 vertexTexCoord;            \n"
            \\in vec4 vertexColor;
            //"out vec2 fragTexCoord;             \n"
            \\out vec4 fragColor;
            //\\uniform mat4 mvp;
            \\void main()
            \\{
            //"    fragTexCoord = vertexTexCoord; \n"
            \\    fragColor = vertexColor / 255.0;
            //\\    fragColor.rgb *= fragColor.a;
            //\\    gl_Position = mvp*vec4(vertexPosition, 1.0); \n"
            \\    gl_Position = vec4(vertexPosition, 1.0);
            \\}
        ;

        const fragSource =
            \\#version 330
            //"in vec2 fragTexCoord;              \n"
            \\in vec4 fragColor;
            \\out vec4 finalColor;
            //"uniform sampler2D texture0;        \n"
            //"uniform vec4 colDiffuse;           \n"
            //"void main()                        \n"
            //"{                                  \n"
            //"    vec4 texelColor = texture(texture0, fragTexCoord);   \n"
            //"    finalColor = texelColor*colDiffuse*fragColor;        \n"
            //"}                                  \n";
            \\void main()
            \\{
            \\    finalColor = fragColor;
            \\}
        ;

        // use default shaders
        const shader = c.LoadShaderFromMemory(vertexSource, fragSource);
        //const shader = c.LoadShaderFromMemory(null, null);

        const VAO = c.rlLoadVertexArray();
        _ = c.rlEnableVertexArray(VAO);

        const VBO = c.rlLoadVertexBuffer(vtx.ptr, @intCast(vtx.len * @sizeOf(dvui.Vertex)), false);
        _ = VBO;
        const EBO = c.rlLoadVertexBufferElement(idx.ptr, @intCast(idx.len * @sizeOf(u32)), false);
        _ = EBO;

        c.rlSetVertexAttribute(@intCast(shader.locs[c.RL_SHADER_LOC_VERTEX_POSITION]), 2, c.RL_FLOAT, false, @sizeOf(dvui.Vertex), @offsetOf(dvui.Vertex, "pos"));
        c.rlEnableVertexAttribute(@intCast(shader.locs[c.RL_SHADER_LOC_VERTEX_POSITION]));

        c.rlSetVertexAttribute(@intCast(shader.locs[c.RL_SHADER_LOC_VERTEX_COLOR]), 4, c.RL_UNSIGNED_BYTE, false, @sizeOf(dvui.Vertex), @offsetOf(dvui.Vertex, "col"));
        c.rlEnableVertexAttribute(@intCast(shader.locs[c.RL_SHADER_LOC_VERTEX_COLOR]));

        c.rlEnableShader(shader.id);

        c.glDrawElements(c.GL_TRIANGLES, @intCast(idx.len), c.GL_UNSIGNED_INT, null);

        c.EndDrawing();
    }

    c.CloseWindow();
}
```

**Comment by VisenDev** [comment]
> Sadly I'm stuck and looking for help. Is there any chance you can try to get that example code working better?

How did you build this? I am struggling to get this to build and link correctly on my machine?

**Comment by david-vanderson** [comment]
It's looking like half my problem is inverted y.

I'm having trouble using raylib as a zig dependency, so I compiled it locally and link the static library just to get going.

```zig
{
        const exe = b.addExecutable(.{
            .name = "raylib-standalone",
            .root_source_file = b.path("raylib-standalone.zig"),
            .target = target,
            .optimize = optimize,
        });

        exe.root_module.addImport("dvui", dvui_mod);
        //exe.root_module.addImport("RaylibBackend", raylib_mod);
        exe.root_module.addIncludePath(b.path("raylib/src"));
        exe.root_module.addObjectFile(b.path("raylib/src/libraylib.a"));
        exe.root_module.linkSystemLibrary("GL", .{});

        const exe_install = b.addInstallArtifact(exe, .{});

        const compile_step = b.step("compile-raylib-standalone", "Compile the Raylib standalone example");
        compile_step.dependOn(&exe_install.step);
        b.getInstallStep().dependOn(compile_step);

        const run_cmd = b.addRunArtifact(exe);
        run_cmd.step.dependOn(compile_step);

        const run_step = b.step("raylib-standalone", "Run the Raylib standalone example");
        run_step.dependOn(&run_cmd.step);
    }
```

**Comment by VisenDev** [comment]
> I'm having trouble using raylib as a zig dependency, so I compiled it locally and link the static library just to get going.

I just realized I wasn't linking "GL"

**Comment by david-vanderson** [comment]
Oh also raylib and dvui both bundle stb_image, so I'm getting duplicate symbols.  For now I'm commenting it out:
```zig
    dvui_mod.addCSourceFiles(.{
        .files = &.{
            //"src/stb/stb_image_impl.c",
            "src/stb/stb_truetype_impl.c",
        },
    });
```

**Comment by VisenDev** [comment]
> Oh also raylib and dvui both bundle stb_image, so I'm getting duplicate symbols. For now I'm commenting it out:

Yes I noticed that as well

**Comment by david-vanderson** [comment]
Aha finally got the thread.  Half was inverted y, the other half was that dvui.pathFillConvex pushes each corner point out "half a pixel", but I hadn't hooked up the matrix stuff yet, so the vertices had small coords that were getting pushed way too far.  Getting there...

**Comment by VisenDev** [comment]
> Getting there...

After looking at it a bit - I'm not gonna be much help in regards to vertex rendering. I've never done 3D graphics before so I am not at all familiar with vertex shaders and rendering.

I will focus on the other raylib-related things

**Comment by david-vanderson** [comment]
That sounds like a plan.  I need to get this cleaned up and merge in the stuff you did and somehow get it compiling for both of us.

In the meantime, here's my renderGeometry function that correctly works (minus textures and scissor);
```zig
    // TODO: scissor
    // TODO: texture
    _ = self;
    _ = texture;

    const vertexSource =
        \\#version 330
        \\in vec3 vertexPosition;
        //"in vec2 vertexTexCoord;            \n"
        \\in vec4 vertexColor;
        //"out vec2 fragTexCoord;             \n"
        \\out vec4 fragColor;
        \\uniform mat4 mvp;
        \\void main()
        \\{
        //"    fragTexCoord = vertexTexCoord; \n"
        \\    fragColor = vertexColor / 255.0;
        //\\    fragColor.rgb *= fragColor.a;
        \\    gl_Position = mvp*vec4(vertexPosition, 1.0);
        //\\    gl_Position = vec4(vertexPosition, 1.0);
        \\}
    ;

    const fragSource =
        \\#version 330
        //"in vec2 fragTexCoord;              \n"
        \\in vec4 fragColor;
        \\out vec4 finalColor;
        //"uniform sampler2D texture0;        \n"
        //"uniform vec4 colDiffuse;           \n"
        //"void main()                        \n"
        //"{                                  \n"
        //"    vec4 texelColor = texture(texture0, fragTexCoord);   \n"
        //"    finalColor = texelColor*colDiffuse*fragColor;        \n"
        //"}                                  \n";
        \\void main()
        \\{
        \\    finalColor = fragColor;
        \\}
    ;

    var mat: c.Matrix = undefined; // = c.GetCameraMatrix2D(camera);
    mat.m0 = 2.0 / @as(f32, @floatFromInt(c.GetRenderWidth()));
    mat.m1 = 0.0;
    mat.m2 = 0.0;
    mat.m3 = 0.0;
    mat.m4 = 0.0;
    mat.m5 = -2.0 / @as(f32, @floatFromInt(c.GetRenderHeight()));
    mat.m6 = 0.0;
    mat.m7 = 0.0;
    mat.m8 = 0.0;
    mat.m9 = 0.0;
    mat.m10 = 1.0;
    mat.m11 = 0.0;
    mat.m12 = -1.0;
    mat.m13 = 1.0;
    mat.m14 = 0.0;
    mat.m15 = 1.0;

    const shader = c.LoadShaderFromMemory(vertexSource, fragSource);

    c.SetShaderValueMatrix(shader, @intCast(shader.locs[c.RL_SHADER_LOC_MATRIX_MVP]), mat);

    const VAO = c.rlLoadVertexArray();
    _ = c.rlEnableVertexArray(VAO);

    const VBO = c.rlLoadVertexBuffer(vtx.ptr, @intCast(vtx.len * @sizeOf(dvui.Vertex)), false);
    _ = VBO;
    const EBO = c.rlLoadVertexBufferElement(idx.ptr, @intCast(idx.len * @sizeOf(u32)), false);
    _ = EBO;

    c.rlSetVertexAttribute(@intCast(shader.locs[c.RL_SHADER_LOC_VERTEX_POSITION]), 2, c.RL_FLOAT, false, @sizeOf(dvui.Vertex), @offsetOf(dvui.Vertex, "pos"));
    c.rlEnableVertexAttribute(@intCast(shader.locs[c.RL_SHADER_LOC_VERTEX_POSITION]));

    c.rlSetVertexAttribute(@intCast(shader.locs[c.RL_SHADER_LOC_VERTEX_COLOR]), 4, c.RL_UNSIGNED_BYTE, false, @sizeOf(dvui.Vertex), @offsetOf(dvui.Vertex, "col"));
    c.rlEnableVertexAttribute(@intCast(shader.locs[c.RL_SHADER_LOC_VERTEX_COLOR]));

    c.rlEnableShader(shader.id);

    c.glDrawElements(c.GL_TRIANGLES, @intCast(idx.len), c.GL_UNSIGNED_INT, null);

```

**Comment by VisenDev** [comment]
Raylib backend now compiles and successfully opens a window
Screenshot_20240730_210421

**Comment by david-vanderson** [comment]
Horay!

**Comment by david-vanderson** [comment]
I've pushed the barest of starts, and tomorrow I'll start integrating the stuff you have here.  Thanks!

**Comment by david-vanderson** [comment]
@VisenDev I've manually merged your stuff into main.  Still very hacky and untested but slowly making progress.  Textures are still eluding me.

**Pull request closed without merging**
